name: Build Alcatraz Loader

on:
  push:
    paths:
      - '**.c'
      - '**.cpp'
      - '**.cxx'
      - '**.h'
      - '**.hpp'
      - '**.hxx'
      - '**.yml'
      - '**/premake*.lua'
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.c'
      - '**.cpp'
      - '**.cxx'
      - '**.h'
      - '**.hpp'
      - '**.hxx'
      - '**.yml'
      - '**/premake*.lua'
      
env:
  SOLUTION_FILE_PATH: project_vs2019_windows/AlcatrazUPlay.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - uses: abel0b/setup-premake@v2.2
      with:
        version: "5.0.0-beta2"
        
    - name: Generate Solution
      working-directory: ${{env.GITHUB_WORKSPACE}}AlcatrazLoader
      run: premake5 vs2019

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}AlcatrazLoader
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: AlcatrazLoader
        path: bin/Release/*.dll
